---
title: "Links"
output: html_document
---

<center><span style="font-family:Didot; font-size:2.5em;">Uttam Banerjee</span></center>
<center><span style="font-family:Didot; font-size:1.5em;">**Github:**[ubanerjee/GasPower](https://github.com/ubanerjee/GasPower)</span></center>
<center><span style="font-family:Didot; font-size:1.5em;">**Email:**[uttam.b@gmail.com](uttam.b@gmail.com)</span></center>
<center><span style="font-family:Didot; font-size:1.5em;">Brampton,ON,Canada
</span></center>

<span style="font-family:Didot; font-size:2em;">Objective</span><br />
Experienced Energy Professional with 10+ years of experience in trading,scheduling and analysing data to improve efficiency of data-driven solutions. Experience in creating demand forecasting and predicting models to implement action-oriented solutions to business problems. Experience with time series analysis and different statistical model. Completed numerous analytical model using R and Python.  Excellent   presentation and communication skill.



<span style="font-family:Didot; font-size:2em;">Towards Certification</span>
<br />
- - - -

**Sheridan College**                                January 2019 - August 2019 
   
Completed Credits towards Certificate Programme leading to **Data Science**

> 1. Bus. Problem & Data Modeling
> 2. Data Explo & Basic Stats
> 3. Advanced Statistics
> 4. Big Data Tools
> 5. Analytics and Machine Learning

<span style="font-family:Didot; font-size:2em;">Experience</span>
<br />

**Chubu TT Energy Management, Brampton,ON**<br />
**Real-Time Energy Trader **                             September 2008 – September 2018 <br />
> * Energy  Trading for CTT Energy Management, Brampton.<br />
> * Advanced understanding of the fundamentals of the IESO, MISO, and NYISO energy market.<br />
> * Efficient Fuel Management of 3x1 ( 900MW ) Goreway Power Station <br />
> * Real-Time energy monitoring for Goreway Power Station, Brampton ( 3x1 Combine Cycle Plant 910 MW ) <br />
> * Energy bidding strategies and Gas scheduling.<br />
> * Coordination with operation department during day to day operation.<br />
> * Submission of DACP/SGOL cost guarantees to the IESO <br />
> * Interpreting energy market fundamentals and resources within Ontario and neighbouring market<br />
> * Provided real time market analysis as part of a team developing daily and long term asset optimization.<br /> 
> * Real-Time Analysis of Electrical and Natural Gas Rate<br /> 
> * Development of Real-Time Performance Analysis Dashboard using the PI real-time data from plant instruments<br />
> * Sound knowledge of North American Electrical and Natural Gas Industry<br />
> * Worked  closely with internal stakeholder (e.g., Risk, Load Forecasting, Finance)<br />
> * Working knowledge of SQL databases, MS Access, Excel , Python  and R <br />


**Project completed using R and Python **
> * Forecasted Ontario Demand with ARIMA model<br />
> * Forecasted Natural gas price<br />
> * Using Chi-Square Test analysed the dependency among combine cycle gas plant<br />
> * Analysing the running trend of gas plant for last five years<br />
> * Using Logistic Regression developed model to predict maintenance schedule<br />


**TECHNICAL EDUCATIONAL QUALIFICATION**<br />
*Credential evaluation report by World Education Services (Ref# 2028043/ssk)*<br />
> * Bachelor's degree in Electrical Engineering<br />
> * Master's in Business Administration – Finance<br />

- - - -
> **Email:** uttam.b@gmail.com<br />
> **Phone:**+1(905)216-3716